### ISSUE TITLE
Chiarimenti su proprietà descrizione di entità spedizione

### ISSUE THREAD

**Issue by f-mancini** [luca-lezzerini/ecommerce-j4j#104]
Che cosa si intende esattamente con la descrizione di una spedizione?
Non sarebbe possibile aggiungere una classe StatiSpedizione che possiede stati boolean che descrivono la tracciabilità (esempio : Non ancora spedito; In preparazione alla spedizione;In spedizione;Spedito)?
Tra l'altro in relazione al ticket #103 si potrebbe andare a ricercare la spedizione per i suddetti stati.

**Comment by luca-lezzerini** [comment]
La descrizione è il tipo di spedizione: es. postale, corriere, ritiro in sede
