### ISSUE TITLE
Commentare anagrafica taglie lato server con javadoc

### ISSUE THREAD

**Issue by MirkoCocchi** [luca-lezzerini/ecommerce-j4j#108]
Il primo dei due che inizia a commentare tolga l'altro dagli assignees

**Comment by serenigianmarco** [comment]
In lavorazione

**Comment by serenigianmarco** [comment]
risolto con commit 9aa3fe2bd25b8b306836ea84b0b3f20d6ab9a23f

**Comment by MirkoCocchi** [comment]
migliorato con commit 01bc6c54f253a7d8cf11c86d91cfee00164e137a
