### ISSUE TITLE
Implementare UC Ricerca

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/ecommerce-j4j#111]
Implementare UC Ricerca
Model.Implementazione.UC Ricerca

**Comment by luca-lezzerini** [comment]
UML aggiornato al commit: 59a39f402212181a4cab609db4ab52d5ed264301

**Comment by Andreadott00** [comment]
risolto 
vedere commit: cfb0b6ca69443c95a69d8bb80262c9bcea148f43
