### ISSUE TITLE
Implementare UC Aggiungi a Carrello

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/ecommerce-j4j#112]
Implementare come previsto da UML Model.Implementazione.UC Aggiungi a Carrello.UC Aggiungi a Carrello.
UML aggiornato al commit: 3be03a45662d6f6eed3b9b14971b8ed170ac1613

**Comment by emanuele-cancelli** [comment]
Preso in carico

**Comment by emanuele-cancelli** [comment]
Chiuso con commit 3e0a511dbece22ec4a76d9450f918a323b095acc
