### ISSUE TITLE
Refactoring chiamate HTTP

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/ecommerce-j4j#113]
Vedere UML Model.Implementazione.Refactoring chiamate POST.
UML disponibile al commit e01454ae035c459e14d39f0f33420f3ca67e8e74

**Comment by Coruxx** [comment]
Effettuato il refactor su tutte le chiamate post tranne che su Anagrafica spedizioni e homepage publica

**Comment by Leonardocaracci** [comment]
chiuso ticket #113 commit d622407d3e87cc8e51d633f3672ceba6e8738690
