### ISSUE TITLE
Implementare UC Visualizza Carrello

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/ecommerce-j4j#115]
Fare riferimento all'UML Model.Implementazione.UC Visualizza Carrello.UC Visualizza Carrello
Commit: 96090f179c331055cc02503d27efe8d782ab88cc

**Comment by Andreadott00** [comment]
Risolto con Commit:  c234f324dd227a16ed27578f2bbdde6d776b79a0
