### ISSUE TITLE
Da sistemare metodo generateNumeroOrdine

### ISSUE THREAD

**Issue by MirkoCocchi** [luca-lezzerini/ecommerce-j4j#121]
Nel metodo generateNumeroOrdine bisogna rendere la visibilità a private, rimuovere il commento al suo interno e commentarlo con javadoc.
Gestire il modo in cui si genera in base alle modifiche

**Comment by emanuele-cancelli** [comment]
Risolto con commit 5cf15dc87d9f718624f8ac5c169862b57b483b5d
