### ISSUE TITLE
Completare Use Case di Home Page

### ISSUE THREAD

**Issue by emanuele-cancelli** [luca-lezzerini/ecommerce-j4j#14]
Descrizione e scenari di Home Page Riservata e Home Page Pubblica

**Comment by luca-lezzerini** [comment]
In lavorazione

**Comment by luca-lezzerini** [comment]
Prevista anche UI

**Comment by luca-lezzerini** [comment]
Create descrizioni, unico scenario, specifiche di implementazione e UI.
Vedere: Model.Implementazione.UC Home Page Pubblica
Commit: 1a70e483543a19a2b1209b119a97954c43ce49c6

**Comment by emanuele-cancelli** [comment]
Aggiungere Controller, Service per Home Page e Repository per Prodotto

**Comment by luca-lezzerini** [comment]
La pagina home non ha bisogno di controller in angular. Inoltre non deve recuperare dati (vedere UML Model.Use Cases.UCs Cliente) in quanto questi vengono gestiti da altri UC.
