### ISSUE TITLE
RegistrazioneResponseDto senza proprietà

### ISSUE THREAD

**Issue by MirkoCocchi** [luca-lezzerini/ecommerce-j4j#16]
Inserire le proprietà di RegistrazioneResponseDto in DTO/Security/Security/RegistrazioneResponseDto

**Comment by luca-lezzerini** [comment]
In lavorazione

**Comment by luca-lezzerini** [comment]
UML aggiornato. Definiti campi del DTO.
Commit: 906cf10fbd496fb8c99d2bcde2f23216631931b8
