### ISSUE TITLE
importare FormsModules

### ISSUE THREAD

**Issue by MirkoCocchi** [luca-lezzerini/ecommerce-j4j#19]
importare FormsModules in client\e-commerce-client\src\app\app.module.ts

**Comment by luca-lezzerini** [comment]
Riassegnato. Lo deve risolvere lei previo accordo con gli altri per evitare conflitti.

**Comment by MirkoCocchi** [comment]
come da accordo, risolvi questo problema tu

**Comment by federicadallavalle** [comment]
Risolto
Commit: 6de431f40eca13bd9de48237351ecaa2cffd4a2d
