### ISSUE TITLE
pulsante registrazione assente - uml

### ISSUE THREAD

**Issue by MirkoCocchi** [luca-lezzerini/ecommerce-j4j#25]
nell'uml sarebbe necessario un pulsante registrazione nella schermata home pubblica e/o nella schermata di login

**Comment by luca-lezzerini** [comment]
Aggiunto pulsante nella finestra login: Model.UI.UI Login 
Committatto UML:  19ba3ca653b49f13cdded6843b2d0644d823d76f
Assegnato a squadra Hispanica

**Comment by f-mancini** [comment]
Aggiungo collaboratore per la richiesta di creazione in UI LOGIN del tasto "registrazione"

**Comment by Picpippo** [comment]
b1d31f19b5c2124b34828ca3ed9d7c85e8f0ef06
