### ISSUE TITLE
UI registrazione-double-optin, registrazione-errore e registrazione-successo mancante

### ISSUE THREAD

**Issue by serenigianmarco** [luca-lezzerini/ecommerce-j4j#31]
Manca l'interfaccia grafica di registrazione-double-optin nell'uml

**Comment by MirkoCocchi** [comment]
Manca l'interfaccia grafica di registrazione-double-optin, registrazione-errore e registrazione-successo nell'uml

**Comment by luca-lezzerini** [comment]
Risolto commit: fc8bf8cf54e3ff5801a5b7ab922de146c7417159
