### ISSUE TITLE
Implementare UC Anagrafica Prodotti

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/ecommerce-j4j#32]
Implementare UC Anagrafica Prodotti.
Si tratta di un CRUD

**Comment by emanuele-cancelli** [comment]
Creato component, realizzata versione parziale del client d5d25ca22fb6b482ac4e3a9bebc3582be8375c7d

**Comment by emanuele-cancelli** [comment]
Creati dto client
Lato server in lavorazione

**Comment by emanuele-cancelli** [comment]
Implementato Controller, Service e ServiceImpl (incompleto)
commit: bbe2693483f91d4b27e669ee125772971b76b1ff

Implementato funzione di ricerca lato client
commit: 80e835c968dd62b1bf7dfeaa80c304bea62d8f14

**Comment by emanuele-cancelli** [comment]
Completato ServiceImpl (da migliorare)
commit: e9c117f83d8f8455e457573e0e9da32ad96952b7

Migliorato ServiceImpl, compleatato Client (da migliorare)
commit: a69043907142f0e0eb5f6b91ac9af52236ebc5b9

**Comment by emanuele-cancelli** [comment]
Completati ultimi miglioramenti e testato
commit: 46e56e0331f9d1cfc7a7989f8b4be698ba729e2a
