### ISSUE TITLE
Aggiungere elementi UML per cambio password

### ISSUE THREAD

**Issue by federicadallavalle** [luca-lezzerini/ecommerce-j4j#33]
Aggiungere:
- Il metodo void reimpostaPassword(ChangePasswordRequestDto) in SecurityController e SecurityService
(Rispettivamente in Model.Controller.Security e Model.Service.Security)
- Il metodo void changePassword(String doi, String password) in UtenteRepository (Model.Repository.Security)
- La classe ChangePasswordRequestDto con proprietà private String doi e private String password in Model.DTO.Security

Linkare ChangePasswordRequestDto in Model.Implementazione.UC Password Dimenticata

**Comment by luca-lezzerini** [comment]
Il metodo void reimpostaPassword(ChangePasswordRequestDto) in SecurityController e SecurityService
(Rispettivamente in Model.Controller.Security e Model.Service.Security): creato solo il controller, il service è ovvio.

Il metodo void changePassword(String doi, String password) in UtenteRepository (Model.Repository.Security): il repository non deve fare queste operazioni complesse in quanto compito del servizio. Il repository deve solo cercare per doi e aggionare il record trovato. Per ora non creiamo repository di update. Non implementato.

La classe ChangePasswordRequestDto con proprietà private String doi e private String password in Model.DTO.Security. E' stata creata in maniera diversa.

**Comment by luca-lezzerini** [comment]
Commit: 779b5ec6c3468a0b922be71d4d199c09f6645584
