### ISSUE TITLE
Component anagrafica spedizioni mancante

### ISSUE THREAD

**Issue by emanuele-cancelli** [luca-lezzerini/ecommerce-j4j#40]
Il component anagrafica spedizioni è stato importato ed è stato creato il routing, ma il component stesso non esiste
Probabilmente non sono stati selezionati i file del component in questo commit 45b16f45a44aa3780ce636ca732f821a03b8bd1a

Procedo ad eliminare gli import e il routing per anagrafica spedizioni

Bisognerà committare il component di nuovo e aggiungere import e routing in app.module.ts

**Comment by AnaKovacevicChisena** [comment]
Risolto con commit 21866c54206eaca9d1db0a396a6bdc315e7f6ae9
