### ISSUE TITLE
Problema pulsanti pagina login

### ISSUE THREAD

**Issue by federicadallavalle** [luca-lezzerini/ecommerce-j4j#41]
Sono necessari due click per i pulsanti "Password dimenticata" e "Registrazione"

**Comment by f-mancini** [comment]
In vista della suddivisione interna del gruppo Hispanica, lascio la gestione del client e di conseguenza del ticket ad altri del gruppo.

**Comment by Picpippo** [comment]
Sistemato:
80b12525a4a5341cb80279868e09966bf610d524
