### ISSUE TITLE
UI registrazione mancanti

### ISSUE THREAD

**Issue by MirkoCocchi** [luca-lezzerini/ecommerce-j4j#42]
completare le UI di registrazione

**Comment by alexgiova** [comment]
In lavorazione UI Registrazione-Double Optin

**Comment by alexgiova** [comment]
Aggiornato html registrarazione-double-optin c1efbcdda01f7cb6275f35b8435109db95743cdb

**Comment by serenigianmarco** [comment]
Aggiornato html registrazione-errore, registrazione-successo
commit 031e47827b2824ce9e568d6da531f32952e59660
