### ISSUE TITLE
Suggerimenti modifiche UML CRUD state diagram e UI CRUD

### ISSUE THREAD

**Issue by federicadallavalle** [luca-lezzerini/ecommerce-j4j#43]
Durante l'implementazione ho riscontrato dei conflitti tra i bottoni dell'UI, in particolare:

- Per visualizzare le righe non è possibile utilizzare view in quanto nel search state è nascosto, si dovrebbe quindi utilizzare cerca con il campo vuoto o spostare il pulsante view accanto a cerca;
- Dal search state non è possibile passare direttamente a edit/delete/view state in quanto i pulsanti sono nascosti (risolvibile implementando il punto precedente);
- I pulsanti rimuovi nel panel, edit e view nella tabella sono ridondanti in quanto è possibile utilizzare quelli nel panel.
I riferimenti alla documentazione: 
Model.Life Cycles.UC CRUD.State Diagram UC CRUD
Model.UI.UI CRUD

**Comment by luca-lezzerini** [comment]
Si decide di lasciare inalterato il modello
