### ISSUE TITLE
metodo verificaToken assente -uml

### ISSUE THREAD

**Issue by MirkoCocchi** [luca-lezzerini/ecommerce-j4j#44]
sarebbe necessario un metodo verificaToken come servizio nel SecurityService per poter verificare se il token è corretto o meno

**Comment by luca-lezzerini** [comment]
Creare in security service un servizio che ritorna un booleano se il token esiste: checkToken (tok: String): Boolean
Vedere in Model.Service.Security
UML aggiornato al commit: c5c09089e65b39335e98eaa8c77dee8b18fefe2b
