### ISSUE TITLE
Verificare proprietà panelEnable in AnagraficaTaglieComponent lato client

### ISSUE THREAD

**Issue by f-mancini** [luca-lezzerini/ecommerce-j4j#46]
Quando possibile, modificare il richiamo della proprietà con il nome corretto

![anataglie](https://user-images.githubusercontent.com/56719527/74551869-50394880-4f54-11ea-92c1-f067b741e156.PNG)

**Comment by MirkoCocchi** [comment]
inizio a modificare

**Comment by MirkoCocchi** [comment]
risolto con commit e13edd69760e1a9d13c74a525be59075c4a04821
