### ISSUE TITLE
Errore nella classe SpedizioniServiceImpl

### ISSUE THREAD

**Issue by MirkoCocchi** [luca-lezzerini/ecommerce-j4j#48]
Errore nella classe com.ai.ecommercej4j.service.impl.SpedizioniServiceImpl lato server nel metodo searchSpedizione.
Variabile da far ritornare non assegnata
`@Override
    public SpedizioneSearchResultsDto searchSpedizione(SpedizioneSearchDto dto) {
        List<Spedizione> ls = new ArrayList<>();
    }`

**Comment by f-mancini** [comment]
ab905100d877379ba17414060562851bbc52581e
