### ISSUE TITLE
Inserire reimpostaPassword nel SecurityService

### ISSUE THREAD

**Issue by Andreadott00** [luca-lezzerini/ecommerce-j4j#53]
sviluppando il reimpostaPassword, mi sono accorto che non e' presente il metodo nel SecurityService dell'UML

**Comment by luca-lezzerini** [comment]
Come spiegato in aula, è corretto che il metodo non ci sia nel security service. I servizi non vengono inseriti nel progetto uml a meno che non sia indispensabile. È compito vostro implementarli in quanto sono ovvi. Quindi può procedere con l'implementazione io aggiornerò il modello successivamente, se lo riterrò opportuno. Commenti con javadoc il servizio in modo che gli altri lo possano utilizzare.

**Comment by Andreadott00** [comment]
implementato d5ff144068fdd3077da3ea925a7f2e49cb0f1bf9
