### ISSUE TITLE
Entità Utente con tutti gli attributi (nullable=false)

### ISSUE THREAD

**Issue by MirkoCocchi** [luca-lezzerini/ecommerce-j4j#55]
Impossibile creare utenti senza aver messo tutti i parametri. Questo è causato dall'annotation @column(nullable=false) nella classe com.ai.ecommercej4j.model.Utente. Anche se l'annotation è messa unicamente sopra id, rende not nullable tutti gli attributi

**Comment by emanuele-cancelli** [comment]
annotation @column(nullable=false) eliminata
commit 3eb5763b70192bf5eb530dadd9ec464ccbc05c72
per oggi è tutto
