### ISSUE TITLE
completare lato client UC anagrafica taglie

### ISSUE THREAD

**Issue by MirkoCocchi** [luca-lezzerini/ecommerce-j4j#56]
completare tutto il  lato client dello use case dell' anagrafica delle taglie

**Comment by sacciuann** [comment]
presa lavorazione

**Comment by sacciuann** [comment]
implementato annulla e view con commit 706c0ff90b1f7ee7e4f6963d6653cbf0ea430554

**Comment by sacciuann** [comment]
implementato funzione edit con commit de19479ef07ba4507dd1d5eb5894ed8ff7fca198

**Comment by MirkoCocchi** [comment]
Implementato metodo delete in anagrafica taglie con commit a77582daa1da176c88505323a130653979addad2

**Comment by MirkoCocchi** [comment]
Chiuso con commit c668baf85543b42b7b1e65fcc8eb08f147550ca3
