### ISSUE TITLE
Implementare prima interfaccia e ts di UC Gestione

### ISSUE THREAD

**Issue by MirkoCocchi** [luca-lezzerini/ecommerce-j4j#64]

**Comment by alexgiova** [comment]
In lavorazione

**Comment by alexgiova** [comment]
Creato il component gestione-offerte
commit 2b52f73dbd94566431764bf798222cdc5b7800f0

**Comment by MirkoCocchi** [comment]
chiuso con f6a29583ef7fc1578ffc821a150fc36ffe407d8d
