### ISSUE TITLE
Inserire attributo offerta alla classe Prodotto

### ISSUE THREAD

**Issue by MirkoCocchi** [luca-lezzerini/ecommerce-j4j#68]

**Comment by emanuele-cancelli** [comment]
Risolto con commit 7e7ebf32e1cef26e82c3ccb19c04905ba379e73c

**Comment by MirkoCocchi** [comment]
Manca la proprietà offerta nella classe prodotto lato client

**Comment by emanuele-cancelli** [comment]
Risolto con commit 96f8ed33c8d7d3b3bf6ac4d2aefc9ded60919ce3
