### ISSUE TITLE
Implementare Web Service per creare dati di test

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/ecommerce-j4j#74]
Il WS deve:

- cancellare i dati esistenti nel DB
- creare due utenti: cliente e gestore, con password uguale al nome utente

Vedere UML: Model.Controller.Development

**Comment by luca-lezzerini** [comment]
Vedere commit 27d024d31b584b33f7c33fa1b0cf107fac678aae per UML aggiornato

**Comment by emanuele-cancelli** [comment]
preso in carico lato client

**Comment by federicadallavalle** [comment]
Risolto commit: 77aff883b38bc91dae9e39648afeada6f4462d5e
url: http://localhost:8080/generate-test-data
