### ISSUE TITLE
Login non rigetta password errata

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/ecommerce-j4j#75]
Creato a mano un utente con username cliente e password psw.
Inserendo le credenziali corrette al login entra in area riservata. Inserendo nome utente corretto e password errata entra lo stesso in area riservata (!!!).
Correggere il bug.

**Comment by luca-lezzerini** [comment]
Angular is running in the development mode. Call enableProdMode() to enable the production mode.
platform-browser.js:1075 Router Event: RoutesRecognized
platform-browser.js:1066 RoutesRecognized(id: 1, url: '/login', urlAfterRedirects: '/login', state: Route(url:'', path:'') { Route(url:'login', path:'login') } )
platform-browser.js:1066 RoutesRecognized
platform-browser.js:1075 Router Event: GuardsCheckStart
platform-browser.js:1066 GuardsCheckStart(id: 1, url: '/login', urlAfterRedirects: '/login', state: Route(url:'', path:'') { Route(url:'login', path:'login') } )
platform-browser.js:1066 GuardsCheckStart
platform-browser.js:1075 Router Event: ChildActivationStart
platform-browser.js:1066 ChildActivationStart(path: '')
platform-browser.js:1066 ChildActivationStart
platform-browser.js:1075 Router Event: ActivationStart
platform-browser.js:1066 ActivationStart(path: 'login')
platform-browser.js:1066 ActivationStart
platform-browser.js:1075 Router Event: GuardsCheckEnd
platform-browser.js:1066 GuardsCheckEnd(id: 1, url: '/login', urlAfterRedirects: '/login', state: Route(url:'', path:'') { Route(url:'login', path:'login') } , shouldActivate: true)
platform-browser.js:1066 GuardsCheckEnd
platform-browser.js:1075 Router Event: ResolveStart
platform-browser.js:1066 ResolveStart(id: 1, url: '/login', urlAfterRedirects: '/login', state: Route(url:'', path:'') { Route(url:'login', path:'login') } )
platform-browser.js:1066 ResolveStart
platform-browser.js:1075 Router Event: ResolveEnd
platform-browser.js:1066 ResolveEnd(id: 1, url: '/login', urlAfterRedirects: '/login', state: Route(url:'', path:'') { Route(url:'login', path:'login') } )
platform-browser.js:1066 ResolveEnd
platform-browser.js:1075 Router Event: ActivationEnd
platform-browser.js:1066 ActivationEnd(path: 'login')
platform-browser.js:1066 ActivationEnd
platform-browser.js:1075 Router Event: ChildActivationEnd
platform-browser.js:1066 ChildActivationEnd(path: '')
platform-browser.js:1066 ChildActivationEnd
platform-browser.js:1075 Router Event: NavigationEnd
platform-browser.js:1066 NavigationEnd(id: 1, url: '/login', urlAfterRedirects: '/login')
platform-browser.js:1066 NavigationEnd
platform-browser.js:1075 Router Event: Scroll
platform-browser.js:1066 Scroll(anchor: 'null', position: 'null')
platform-browser.js:1066 Scroll
platform-browser.js:1075 Router Event: Scroll
platform-browser.js:1066 Scroll(anchor: 'null', position: 'null')
platform-browser.js:1066 Scroll
client:52 [WDS] Live Reloading enabled.
platform-browser.js:1075 Router Event: NavigationStart
platform-browser.js:1066 NavigationStart(id: 2, url: '/home-riservata')
platform-browser.js:1066 NavigationStart
platform-browser.js:1075 Router Event: RoutesRecognized
platform-browser.js:1066 RoutesRecognized(id: 2, url: '/home-riservata', urlAfterRedirects: '/home-riservata', state: Route(url:'', path:'') { Route(url:'home-riservata', path:'home-riservata') } )
platform-browser.js:1066 RoutesRecognized
platform-browser.js:1075 Router Event: GuardsCheckStart
platform-browser.js:1066 GuardsCheckStart(id: 2, url: '/home-riservata', urlAfterRedirects: '/home-riservata', state: Route(url:'', path:'') { Route(url:'home-riservata', path:'home-riservata') } )
platform-browser.js:1066 GuardsCheckStart
platform-browser.js:1075 Router Event: ChildActivationStart
platform-browser.js:1066 ChildActivationStart(path: '')
platform-browser.js:1066 ChildActivationStart
platform-browser.js:1075 Router Event: ActivationStart
platform-browser.js:1066 ActivationStart(path: 'home-riservata')
platform-browser.js:1066 ActivationStart
platform-browser.js:1075 Router Event: GuardsCheckEnd
platform-browser.js:1066 GuardsCheckEnd(id: 2, url: '/home-riservata', urlAfterRedirects: '/home-riservata', state: Route(url:'', path:'') { Route(url:'home-riservata', path:'home-riservata') } , shouldActivate: true)
platform-browser.js:1066 GuardsCheckEnd
platform-browser.js:1075 Router Event: ResolveStart
platform-browser.js:1066 ResolveStart(id: 2, url: '/home-riservata', urlAfterRedirects: '/home-riservata', state: Route(url:'', path:'') { Route(url:'home-riservata', path:'home-riservata') } )
platform-browser.js:1066 ResolveStart
platform-browser.js:1075 Router Event: ResolveEnd
platform-browser.js:1066 ResolveEnd(id: 2, url: '/home-riservata', urlAfterRedirects: '/home-riservata', state: Route(url:'', path:'') { Route(url:'home-riservata', path:'home-riservata') } )
platform-browser.js:1066 ResolveEnd
platform-browser.js:1075 Router Event: ActivationEnd
platform-browser.js:1066 ActivationEnd(path: 'home-riservata')
platform-browser.js:1066 ActivationEnd
platform-browser.js:1075 Router Event: ChildActivationEnd
platform-browser.js:1066 ChildActivationEnd(path: '')
platform-browser.js:1066 ChildActivationEnd
platform-browser.js:1075 Router Event: NavigationEnd
platform-browser.js:1066 NavigationEnd(id: 2, url: '/home-riservata', urlAfterRedirects: '/home-riservata')
platform-browser.js:1066 NavigationEnd
platform-browser.js:1075 Router Event: Scroll
platform-browser.js:1066 Scroll(anchor: 'null', position: 'null')
platform-browser.js:1066 Scroll
platform-browser.js:1075 Router Event: Scroll
platform-browser.js:1066 Scroll(anchor: 'null', position: 'null')
platform-browser.js:1066 Scroll
platform-browser.js:1075 Router Event: NavigationStart
platform-browser.js:1066 NavigationStart(id: 3, url: '/login')
platform-browser.js:1066 NavigationStart
platform-browser.js:1075 Router Event: RoutesRecognized
platform-browser.js:1066 RoutesRecognized(id: 3, url: '/login', urlAfterRedirects: '/login', state: Route(url:'', path:'') { Route(url:'login', path:'login') } )
platform-browser.js:1066 RoutesRecognized
platform-browser.js:1075 Router Event: GuardsCheckStart
platform-browser.js:1066 GuardsCheckStart(id: 3, url: '/login', urlAfterRedirects: '/login', state: Route(url:'', path:'') { Route(url:'login', path:'login') } )
platform-browser.js:1066 GuardsCheckStart
platform-browser.js:1075 Router Event: ChildActivationStart
platform-browser.js:1066 ChildActivationStart(path: '')
platform-browser.js:1066 ChildActivationStart
platform-browser.js:1075 Router Event: ActivationStart
platform-browser.js:1066 ActivationStart(path: 'login')
platform-browser.js:1066 ActivationStart
platform-browser.js:1075 Router Event: GuardsCheckEnd
platform-browser.js:1066 GuardsCheckEnd(id: 3, url: '/login', urlAfterRedirects: '/login', state: Route(url:'', path:'') { Route(url:'login', path:'login') } , shouldActivate: true)
platform-browser.js:1066 GuardsCheckEnd
platform-browser.js:1075 Router Event: ResolveStart
platform-browser.js:1066 ResolveStart(id: 3, url: '/login', urlAfterRedirects: '/login', state: Route(url:'', path:'') { Route(url:'login', path:'login') } )
platform-browser.js:1066 ResolveStart
platform-browser.js:1075 Router Event: ResolveEnd
platform-browser.js:1066 ResolveEnd(id: 3, url: '/login', urlAfterRedirects: '/login', state: Route(url:'', path:'') { Route(url:'login', path:'login') } )
platform-browser.js:1066 ResolveEnd
platform-browser.js:1075 Router Event: ActivationEnd
platform-browser.js:1066 ActivationEnd(path: 'login')
platform-browser.js:1066 ActivationEnd
platform-browser.js:1075 Router Event: ChildActivationEnd
platform-browser.js:1066 ChildActivationEnd(path: '')
platform-browser.js:1066 ChildActivationEnd
platform-browser.js:1075 Router Event: NavigationEnd
platform-browser.js:1066 NavigationEnd(id: 3, url: '/login', urlAfterRedirects: '/login')
platform-browser.js:1066 NavigationEnd
platform-browser.js:1075 Router Event: Scroll
platform-browser.js:1066 Scroll(anchor: 'null', position: '0, 0')
platform-browser.js:1066 Scroll
platform-browser.js:1075 Router Event: Scroll
platform-browser.js:1066 Scroll(anchor: 'null', position: '0, 0')
platform-browser.js:1066 Scroll
platform-browser.js:1075 Router Event: NavigationStart
platform-browser.js:1066 NavigationStart(id: 4, url: '/home-riservata')
platform-browser.js:1066 NavigationStart
platform-browser.js:1075 Router Event: RoutesRecognized
platform-browser.js:1066 RoutesRecognized(id: 4, url: '/home-riservata', urlAfterRedirects: '/home-riservata', state: Route(url:'', path:'') { Route(url:'home-riservata', path:'home-riservata') } )
platform-browser.js:1066 RoutesRecognized
platform-browser.js:1075 Router Event: GuardsCheckStart
platform-browser.js:1066 GuardsCheckStart(id: 4, url: '/home-riservata', urlAfterRedirects: '/home-riservata', state: Route(url:'', path:'') { Route(url:'home-riservata', path:'home-riservata') } )
platform-browser.js:1066 GuardsCheckStart
platform-browser.js:1075 Router Event: ChildActivationStart
platform-browser.js:1066 ChildActivationStart(path: '')
platform-browser.js:1066 ChildActivationStart
platform-browser.js:1075 Router Event: ActivationStart
platform-browser.js:1066 ActivationStart(path: 'home-riservata')
platform-browser.js:1066 ActivationStart
platform-browser.js:1075 Router Event: GuardsCheckEnd
platform-browser.js:1066 GuardsCheckEnd(id: 4, url: '/home-riservata', urlAfterRedirects: '/home-riservata', state: Route(url:'', path:'') { Route(url:'home-riservata', path:'home-riservata') } , shouldActivate: true)
platform-browser.js:1066 GuardsCheckEnd
platform-browser.js:1075 Router Event: ResolveStart
platform-browser.js:1066 ResolveStart(id: 4, url: '/home-riservata', urlAfterRedirects: '/home-riservata', state: Route(url:'', path:'') { Route(url:'home-riservata', path:'home-riservata') } )
platform-browser.js:1066 ResolveStart
platform-browser.js:1075 Router Event: ResolveEnd
platform-browser.js:1066 ResolveEnd(id: 4, url: '/home-riservata', urlAfterRedirects: '/home-riservata', state: Route(url:'', path:'') { Route(url:'home-riservata', path:'home-riservata') } )
platform-browser.js:1066 ResolveEnd
platform-browser.js:1075 Router Event: ActivationEnd
platform-browser.js:1066 ActivationEnd(path: 'home-riservata')
platform-browser.js:1066 ActivationEnd
platform-browser.js:1075 Router Event: ChildActivationEnd
platform-browser.js:1066 ChildActivationEnd(path: '')
platform-browser.js:1066 ChildActivationEnd
platform-browser.js:1075 Router Event: NavigationEnd
platform-browser.js:1066 NavigationEnd(id: 4, url: '/home-riservata', urlAfterRedirects: '/home-riservata')
platform-browser.js:1066 NavigationEnd
platform-browser.js:1075 Router Event: Scroll
platform-browser.js:1066 Scroll(anchor: 'null', position: 'null')
platform-browser.js:1066 Scroll
platform-browser.js:1075 Router Event: Scroll
platform-browser.js:1066 Scroll(anchor: 'null', position: 'null')
platform-browser.js:1066 Scroll

**Comment by alexgiova** [comment]
In lavorazione

**Comment by alexgiova** [comment]
Implementato il metodo login di login.component.ts
Ripuliti i campi username e password
commit 61724754f37f2cb520efaee01ff918482897b9f4
