### ISSUE TITLE
UC Anagrafica colori: mancano le etichette prima dei campi

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/ecommerce-j4j#76]
I campi di input in aggiungi, modifica, visualizza e conferma cancellazione non hanno le etichette con l'indicazione del nome del campo.

**Comment by luca-lezzerini** [comment]
![Clipboard01](https://user-images.githubusercontent.com/47611629/74659251-469e2380-5194-11ea-8cbf-01d09000ca33.png)

**Comment by nicolas-bovolenta** [comment]
risolto 
vedere commit: f995e0e748ab7b41ed248f16c4c0e134a8d0e91b
