### ISSUE TITLE
UC Anagrafica Colori ha campi editabili in view mode

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/ecommerce-j4j#78]
Se si entra in visualizzazione i campi sono modificabili mentre non dovrebbero esserlo
![Clipboard03](https://user-images.githubusercontent.com/47611629/74659567-e2c82a80-5194-11ea-805c-0c599a85feb5.png)

**Comment by nicolas-bovolenta** [comment]
risolto 
vedere commit: 5ae7c8f82672008680d6e106c32acdf032c244b7
