### ISSUE TITLE
UC Anagrafica Colori: non crea da visualizza

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/ecommerce-j4j#79]
Cliccando Visualizza su una riga non è poi possibile creare un nuovo elemento cliccando su Crea.

**Comment by MirkoCocchi** [comment]
inizio risoluzione problema

**Comment by MirkoCocchi** [comment]
Il problema risulta gia risolto con il commit 29ba3a0bce4c9e8227bb232c46f5cef5eff66e25
