### ISSUE TITLE
Generazione dati di test non cancella entità taglie

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/ecommerce-j4j#96]
Se si creano delle taglie e poi si rigenerano i dati di test, le taglie rimangono mentre dovrebbero essere rimosse. Probabilmente accade anche per altre entità.

**Comment by emanuele-cancelli** [comment]
Risolto con commit 01e57e60011d5d358c4fb8362e7ff9aafc5a57ec
