### ISSUE TITLE
Se l'utente non è loggato si accede allo UC Anagrafica Taglie

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/ecommerce-j4j#98]
Il sistema dovrebbe proporre la finestra di login in caso di utente non loggato

**Comment by alexgiova** [comment]
In lavorazione

**Comment by alexgiova** [comment]
L'utente non registrato non accede ad anagrafica-taglie ma viene rimandato alla pagina di Login
Commit 6993c2d1c7bc52bc9d2fca7bd88781db0da7ae45
